/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class BookSchema extends BaseModel {
  static $columns = ['author', 'createdAt', 'id', 'isbn', 'price', 'stock', 'title', 'updatedAt'] as const
  $columns = BookSchema.$columns
  @column()
  declare author: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isbn: string
  @column()
  declare price: number
  @column()
  declare stock: number
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CustomerSchema extends BaseModel {
  static $columns = ['address', 'createdAt', 'email', 'fullName', 'id', 'phone', 'updatedAt'] as const
  $columns = CustomerSchema.$columns
  @column()
  declare address: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare phone: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SaleDetailSchema extends BaseModel {
  static $columns = ['bookId', 'createdAt', 'id', 'lineTotal', 'quantity', 'saleId', 'unitPrice', 'updatedAt'] as const
  $columns = SaleDetailSchema.$columns
  @column()
  declare bookId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare lineTotal: number
  @column()
  declare quantity: number
  @column()
  declare saleId: number
  @column()
  declare unitPrice: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SaleSchema extends BaseModel {
  static $columns = ['createdAt', 'customerId', 'id', 'saleDate', 'totalAmount', 'updatedAt'] as const
  $columns = SaleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare customerId: number
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare saleDate: DateTime
  @column()
  declare totalAmount: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
